[package]
name = "music-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
music-agent = { workspace = true }
music-analysis-client = { workspace = true }
music-domain = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
